import type { ReceiptInput } from './types';

type ReceiptTemplate = Omit<ReceiptInput, 'user_id'>;

export const receiptCatalog = {
  cardAuthHold: (params: { merchant: string; amount_cents: number; external_id: string }): ReceiptTemplate => ({
    type: 'auth_hold',
    title: params.merchant,
    subtitle: 'Card authorization',
    amount_cents: -Math.abs(params.amount_cents),
    metadata: {
      external_id: params.external_id,
      what_happened: 'Authorization placed.',
      what_changed: 'Hold created.',
      whats_next: 'Settlement or release is next.',
    },
  }),
  cardAuthDeclined: (params: { merchant: string; amount_cents: number; reason?: string; external_id: string }): ReceiptTemplate => ({
    type: 'auth_declined',
    title: params.merchant,
    subtitle: params.reason || 'Authorization declined',
    amount_cents: 0,
    metadata: {
      external_id: params.external_id,
      what_happened: 'Authorization declined.',
      what_changed: 'No balance change.',
      whats_next: 'Try again or use another card.',
    },
  }),
  cardSettlement: (params: { merchant: string; amount_cents: number; external_id: string }): ReceiptTemplate => ({
    type: 'settlement',
    title: params.merchant,
    subtitle: 'Settlement posted',
    amount_cents: -Math.abs(params.amount_cents),
    metadata: {
      external_id: params.external_id,
      what_happened: 'Card settlement posted.',
      what_changed: 'Cash balance decreased.',
      whats_next: 'Receipt is final.',
    },
  }),
  cardReversal: (params: { external_id: string }): ReceiptTemplate => ({
    type: 'reversal',
    title: 'Authorization released',
    subtitle: 'Hold removed',
    amount_cents: 0,
    metadata: {
      external_id: params.external_id,
      what_happened: 'Authorization reversed.',
      what_changed: 'Hold released.',
      whats_next: 'Spendable restored.',
    },
  }),
  cardRefund: (params: { merchant: string; amount_cents: number; external_id: string }): ReceiptTemplate => ({
    type: 'refund',
    title: params.merchant,
    subtitle: 'Refund posted',
    amount_cents: Math.abs(params.amount_cents),
    metadata: {
      external_id: params.external_id,
      what_happened: 'Refund posted.',
      what_changed: 'Cash balance increased.',
      whats_next: 'Funds are available now.',
    },
  }),
  cardDispute: (params: { reason?: string; external_id: string }): ReceiptTemplate => ({
    type: 'dispute',
    title: 'Dispute filed',
    subtitle: params.reason || 'Card dispute',
    amount_cents: 0,
    metadata: {
      external_id: params.external_id,
      what_happened: 'Dispute opened.',
      what_changed: 'Funds under review.',
      whats_next: 'We will notify you with the outcome.',
    },
  }),
  achPending: (params: { direction: 'credit' | 'debit'; amount_cents: number; external_id: string }): ReceiptTemplate => ({
    type: params.direction === 'credit' ? 'deposit_pending' : 'transfer_pending',
    title: params.direction === 'credit' ? 'Deposit pending' : 'Transfer pending',
    subtitle: params.direction === 'credit' ? 'ACH pending' : 'ACH pending',
    amount_cents: params.direction === 'credit' ? Math.abs(params.amount_cents) : -Math.abs(params.amount_cents),
    metadata: {
      external_id: params.external_id,
      what_happened: 'ACH pending.',
      what_changed: 'No balance change yet.',
      whats_next: 'Funds will post once settled.',
    },
  }),
  achPosted: (params: { direction: 'credit' | 'debit'; amount_cents: number; external_id: string }): ReceiptTemplate => ({
    type: params.direction === 'credit' ? 'deposit_posted' : 'transfer',
    title: params.direction === 'credit' ? 'Deposit' : 'ACH withdrawal',
    subtitle: params.direction === 'credit' ? 'Funds added' : 'Transfer out',
    amount_cents: params.direction === 'credit' ? Math.abs(params.amount_cents) : -Math.abs(params.amount_cents),
    metadata: {
      external_id: params.external_id,
      what_happened: params.direction === 'credit' ? 'Deposit posted.' : 'ACH withdrawal posted.',
      what_changed: params.direction === 'credit' ? 'Cash balance increased.' : 'Cash balance decreased.',
      whats_next: params.direction === 'credit' ? 'Funds are spendable now.' : 'Funds are outbound.',
    },
  }),
  achReturn: (params: { direction: 'credit' | 'debit'; amount_cents: number; external_id: string }): ReceiptTemplate => ({
    type: 'ach_return',
    title: 'ACH return',
    subtitle: 'Transfer reversed',
    amount_cents: params.direction === 'credit' ? -Math.abs(params.amount_cents) : Math.abs(params.amount_cents),
    metadata: {
      external_id: params.external_id,
      what_happened: 'ACH returned.',
      what_changed: 'Cash balance adjusted.',
      whats_next: 'Contact support if unexpected.',
    },
  }),
  tradeQueued: (params: { symbol: string; amount_cents: number; external_id: string }): ReceiptTemplate => ({
    type: 'trade_queued',
    title: `${params.symbol} trade queued`,
    subtitle: 'Awaiting fill',
    amount_cents: -Math.abs(params.amount_cents),
    metadata: {
      external_id: params.external_id,
      what_happened: 'Trade queued.',
      what_changed: 'No balance change yet.',
      whats_next: 'We will update once filled.',
    },
  }),
  tradeFilled: (params: { symbol: string; amount_cents: number; side: 'buy' | 'sell'; external_id: string }): ReceiptTemplate => ({
    type: 'trade_filled',
    title: params.symbol,
    subtitle: params.side === 'buy' ? 'Trade filled' : 'Trade sold',
    amount_cents: params.side === 'buy' ? -Math.abs(params.amount_cents) : Math.abs(params.amount_cents),
    metadata: {
      external_id: params.external_id,
      side: params.side,
      what_happened: 'Trade filled.',
      what_changed: params.side === 'buy' ? 'Cash moved into investments.' : 'Cash released from holdings.',
      whats_next: 'Holdings updated.',
    },
  }),
  tradeFailed: (params: { symbol: string; amount_cents: number; external_id: string }): ReceiptTemplate => ({
    type: 'trade_failed',
    title: `${params.symbol} trade failed`,
    subtitle: 'Order failed',
    amount_cents: 0,
    metadata: {
      external_id: params.external_id,
      what_happened: 'Trade failed.',
      what_changed: 'No balance change.',
      whats_next: 'Retry or contact support.',
    },
  }),
  liquidationQueued: (params: { amount_cents: number; reason: string; external_id: string }): ReceiptTemplate => ({
    type: 'liquidation_queued',
    title: 'Liquidation queued',
    subtitle: params.reason,
    amount_cents: params.amount_cents,
    metadata: {
      external_id: params.external_id,
      what_happened: 'Liquidation queued.',
      what_changed: 'No immediate sale executed.',
      whats_next: 'We will sell at next window.',
    },
  }),
  liquidationCompleted: (params: { amount_cents: number; external_id: string }): ReceiptTemplate => ({
    type: 'liquidation_completed',
    title: 'Liquidation complete',
    subtitle: 'Balance restored',
    amount_cents: params.amount_cents,
    metadata: {
      external_id: params.external_id,
      what_happened: 'Liquidation executed.',
      what_changed: 'Cash balance increased.',
      whats_next: 'Spendable restored.',
    },
  }),
  reconcileDrift: (params: { drift_cents: number; external_id: string }): ReceiptTemplate => ({
    type: 'reconcile_drift',
    title: 'Reconciliation drift',
    subtitle: 'Difference detected',
    amount_cents: 0,
    metadata: {
      external_id: params.external_id,
      drift_cents: params.drift_cents,
      what_happened: 'Partner balance drift detected.',
      what_changed: 'No ledger change yet.',
      whats_next: 'Operator review required.',
    },
  }),
  reconcileCleared: (params: { external_id: string }): ReceiptTemplate => ({
    type: 'reconcile_cleared',
    title: 'Reconciliation clear',
    subtitle: 'No drift detected',
    amount_cents: 0,
    metadata: {
      external_id: params.external_id,
      what_happened: 'Balances match.',
      what_changed: 'No ledger change.',
      whats_next: 'Monitoring continues.',
    },
  }),
  supportRequest: (): ReceiptTemplate => ({
    type: 'support_request',
    title: 'Support',
    subtitle: 'We will reach out shortly.',
    amount_cents: 0,
    metadata: {
      what_happened: 'Support request opened.',
      what_changed: 'No balance change.',
      whats_next: 'A Bloom specialist will contact you.',
    },
  }),
  transferRequest: (params: { amount_cents: number; external_id: string }): ReceiptTemplate => ({
    type: 'transfer_request',
    title: 'Transfer requested',
    subtitle: 'Awaiting processing',
    amount_cents: params.amount_cents,
    metadata: {
      external_id: params.external_id,
      what_happened: 'Transfer request created.',
      what_changed: 'No balance change yet.',
      whats_next: 'Funds will move when processed.',
    },
  }),
  policyBufferUpdated: (params: { amount_cents: number; external_id: string }): ReceiptTemplate => ({
    type: 'policy_update',
    title: 'Buffer updated',
    subtitle: 'Savings buffer set',
    amount_cents: params.amount_cents,
    metadata: {
      external_id: params.external_id,
      what_happened: 'Buffer updated.',
      what_changed: 'Spendable policy adjusted.',
      whats_next: 'New buffer applies immediately.',
    },
  }),
  allocationSet: (params: { label: string; external_id: string }): ReceiptTemplate => ({
    type: 'allocation_set',
    title: 'Allocation set',
    subtitle: params.label,
    amount_cents: 0,
    metadata: {
      external_id: params.external_id,
      what_happened: 'Allocation updated.',
      what_changed: 'Targets stored.',
      whats_next: 'Execute allocation when ready.',
    },
  }),
  cardFreeze: (params: { external_id: string }): ReceiptTemplate => ({
    type: 'card_freeze',
    title: 'Card freeze requested',
    subtitle: 'Pending write access',
    amount_cents: 0,
    metadata: {
      external_id: params.external_id,
      what_happened: 'Card control requested.',
      what_changed: 'Awaiting processor write access.',
      whats_next: 'We will apply once enabled.',
    },
  }),
  cardUnfreeze: (params: { external_id: string }): ReceiptTemplate => ({
    type: 'card_unfreeze',
    title: 'Card unfreeze requested',
    subtitle: 'Pending write access',
    amount_cents: 0,
    metadata: {
      external_id: params.external_id,
      what_happened: 'Card control requested.',
      what_changed: 'Awaiting processor write access.',
      whats_next: 'We will apply once enabled.',
    },
  }),
  convert: (params: { from: string; to: string; amount_cents: number; external_id: string }): ReceiptTemplate => ({
    type: 'convert',
    title: `Converted ${params.from} to ${params.to}`,
    subtitle: 'Conversion executed',
    amount_cents: params.amount_cents,
    metadata: {
      external_id: params.external_id,
      what_happened: 'Conversion filled.',
      what_changed: `${params.from} reduced, ${params.to} increased.`,
      whats_next: 'Holdings updated.',
    },
  }),
};
